version: "3"

services:

  backend:
    container_name: backend
    build:
      context: ./server
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./build:/build:ro
      - ./yolov5l.pt:/./yolov5l.pt
    depends_on:
      - elasticsearch

    environment:
      - API_PORT=$API_PORT
      - DATABASE_SCHEME=$DATABASE_SCHEME
      - DATABASE_ADDRESS=$DATABASE_ADDRESS
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
    networks:
      - net
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=$DATABASE_PASSWORD
      - ELASTIC_USERNAME=$DATABASE_USER
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    command: ["elasticsearch", "-Elogger.level=WARN"]
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cat/nodes?v\\&pretty || exit 1" ]
    networks:
      - net

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./build:/build:ro
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - net
volumes:
  esdata:

networks:
  net:
    driver: bridge