---
swagger: "2.0"
info:
  description: "Book recommendations service"
  version: "1.0.0"
  title: "Book recommendations service"
tags:
- name: "recommendations"
schemes:
- "https"
- "http"
basePath: /api/v1/
paths:
  /recommendations:
    post:
      tags:
      - "recommendations"
      summary: "Send image and receive recommendations"
      operationId: "get_recommendations"
      consumes:
        - application/json
      produces:
          - application/json
      parameters: 
      - in: body
        schema:
            type: object
            properties:
              id:
                type: string
              image:
                type: string
        name: "body"
        required: true
        
      responses:
        "200":
          description: "Success"
          schema:
            type: "array"
            items:
              type: "string"
        "400":
          description: "Something went wrong"
      x-swagger-router-controller: "src.api.controllers.recommendations_controller"
      
  /book:
    post:
      tags:
      - "book"
      summary: "Detect book on image"
      operationId: "detect_book"
      consumes:
        - application/json
      produces:
          - application/json
      parameters: 
      - in: body
        schema:
            type: object
            properties:
              id:
                type: string
              image:
                type: string
              book_id:
                type: string
        name: "body"
        required: true
        
      responses:
        "200":
          description: "Success"
          schema:
            type: "array"
            items:
              type: "string"
        "400":
          description: "Something went wrong"
      x-swagger-router-controller: "src.api.controllers.detect_book_controller"
      
